import './reset.css'
import './header.css'


export const metadata = {
  title: 'My-blog',
  description: 'Generated by create youngmin',
}

export default function RootLayout({ children }) {
  const base_url = 'http://127.0.0.1:8000/' + 'post/'
  return (
    <html>
      <header>
        <div className='nav-bar'>
          <div className='nav-container'>
            <div className='nav-img'>
              <img src='/blog_img_white.svg'></img>
            </div>
          </div>
          <div className='nav-toolbar'>
            <div className='nav-topics'>
              <a href={base_url}>컴퓨터사이언스</a>
              <a href="">알고리즘</a>
              <a href="">Python</a>
              <a href="">Django</a>
              <a href="">React</a>
              <a href="">Next.JS</a>
            </div>
            <div className='nav-buttons'>
              <a className='primary-button' href="">Login</a>
            </div>
          </div>
        </div>
      </header>
      {children}
    </html>
  )
}
